"""Add system settings table

Revision ID: 2842f356c238
Revises: 4ba1dfea6298
Create Date: 2025-12-22 21:38:05.606014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2842f356c238'
down_revision = '4ba1dfea6298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=True),
    sa.Column('site_description', sa.String(length=255), nullable=True),
    sa.Column('site_keywords', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('max_upload_size', sa.Integer(), nullable=True),
    sa.Column('per_page', sa.Integer(), nullable=True),
    sa.Column('bcrypt_log_rounds', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
