"""完善Project模型字段

Revision ID: 44f54e3bdefe
Revises: 1ab9295390da
Create Date: 2026-06-15 21:03:38.084005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f54e3bdefe'
down_revision = '1ab9295390da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bugs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_bugs_team_id'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.create_index(batch_op.f('ix_bugs_bug_code'), ['bug_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_bugs_status'), ['status'], unique=False)

    with op.batch_alter_table('code_commits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_commit_hash'))
        batch_op.create_index(batch_op.f('ix_code_commits_commit_hash'), ['commit_hash'], unique=False)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('course_code'))
        batch_op.drop_index(batch_op.f('idx_course_code'))
        batch_op.drop_index(batch_op.f('idx_course_name'))
        batch_op.drop_index(batch_op.f('idx_semester'))
        batch_op.drop_index(batch_op.f('idx_year'))
        batch_op.create_index(batch_op.f('ix_courses_course_code'), ['course_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_courses_course_name'), ['course_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_semester'), ['semester'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_year'), ['year'], unique=False)

    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_daily_reports_team_id'))
        batch_op.drop_index(batch_op.f('idx_report_date'))
        batch_op.create_index(batch_op.f('ix_daily_reports_report_date'), ['report_date'], unique=False)

    with op.batch_alter_table('project_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_name'))
        batch_op.create_index(batch_op.f('ix_project_templates_name'), ['name'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leader_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tech_stack', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('deploy_url', sa.String(length=255), nullable=True))
        batch_op.drop_index(batch_op.f('idx_name'))
        batch_op.drop_index(batch_op.f('idx_project_code'))
        batch_op.drop_index(batch_op.f('idx_projects_course_id'))
        batch_op.drop_index(batch_op.f('idx_projects_teacher_id'))
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('project_code'))
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_project_code'), ['project_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)
        batch_op.create_foreign_key(None, 'students', ['leader_id'], ['id'])

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_semester'))
        batch_op.drop_index(batch_op.f('idx_year'))
        batch_op.create_index(batch_op.f('ix_scores_semester'), ['semester'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_year'), ['year'], unique=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_class_name'))
        batch_op.drop_index(batch_op.f('idx_major'))
        batch_op.drop_index(batch_op.f('idx_name'))
        batch_op.drop_index(batch_op.f('idx_student_id'))
        batch_op.drop_index(batch_op.f('student_id'))
        batch_op.create_index(batch_op.f('ix_students_class_name'), ['class_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_major'), ['major'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_student_id'), ['student_id'], unique=True)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_status'))
        batch_op.drop_index(batch_op.f('idx_task_code'))
        batch_op.drop_index(batch_op.f('idx_tasks_team_id'))
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_task_code'), ['task_code'], unique=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_teams_project_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_role'))
        batch_op.drop_index(batch_op.f('idx_username'))
        batch_op.drop_index(batch_op.f('username'))
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('idx_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_role'), ['role'], unique=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_teams_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_task_code'))
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.create_index(batch_op.f('idx_tasks_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_task_code'), ['task_code'], unique=False)
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_student_id'))
        batch_op.drop_index(batch_op.f('ix_students_name'))
        batch_op.drop_index(batch_op.f('ix_students_major'))
        batch_op.drop_index(batch_op.f('ix_students_class_name'))
        batch_op.create_index(batch_op.f('student_id'), ['student_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('idx_major'), ['major'], unique=False)
        batch_op.create_index(batch_op.f('idx_class_name'), ['class_name'], unique=False)

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_year'))
        batch_op.drop_index(batch_op.f('ix_scores_semester'))
        batch_op.create_index(batch_op.f('idx_year'), ['year'], unique=False)
        batch_op.create_index(batch_op.f('idx_semester'), ['semester'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_project_code'))
        batch_op.drop_index(batch_op.f('ix_projects_name'))
        batch_op.create_index(batch_op.f('project_code'), ['project_code'], unique=True)
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_projects_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_projects_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_project_code'), ['project_code'], unique=False)
        batch_op.create_index(batch_op.f('idx_name'), ['name'], unique=False)
        batch_op.drop_column('deploy_url')
        batch_op.drop_column('tech_stack')
        batch_op.drop_column('leader_id')

    with op.batch_alter_table('project_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_templates_name'))
        batch_op.create_index(batch_op.f('idx_name'), ['name'], unique=False)

    with op.batch_alter_table('daily_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_reports_report_date'))
        batch_op.create_index(batch_op.f('idx_report_date'), ['report_date'], unique=False)
        batch_op.create_index(batch_op.f('idx_daily_reports_team_id'), ['team_id'], unique=False)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_year'))
        batch_op.drop_index(batch_op.f('ix_courses_semester'))
        batch_op.drop_index(batch_op.f('ix_courses_course_name'))
        batch_op.drop_index(batch_op.f('ix_courses_course_code'))
        batch_op.create_index(batch_op.f('idx_year'), ['year'], unique=False)
        batch_op.create_index(batch_op.f('idx_semester'), ['semester'], unique=False)
        batch_op.create_index(batch_op.f('idx_course_name'), ['course_name'], unique=False)
        batch_op.create_index(batch_op.f('idx_course_code'), ['course_code'], unique=False)
        batch_op.create_index(batch_op.f('course_code'), ['course_code'], unique=True)

    with op.batch_alter_table('code_commits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_code_commits_commit_hash'))
        batch_op.create_index(batch_op.f('idx_commit_hash'), ['commit_hash'], unique=False)

    with op.batch_alter_table('bugs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bugs_status'))
        batch_op.drop_index(batch_op.f('ix_bugs_bug_code'))
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_bugs_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###
