"""修改Course表的teacher_id外键约束

Revision ID: 4ba1dfea6298
Revises: 4494378494fe
Create Date: 2025-12-19 17:53:23.400447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ba1dfea6298'
down_revision = '4494378494fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('teacher_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('courses_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['teacher_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('courses_ibfk_1'), 'users', ['teacher_id'], ['id'])
        batch_op.alter_column('teacher_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
