"""完善任务表字段

Revision ID: 5ba2dfea6299
Revises: 44f54e3bdefe
Create Date: 2026-06-16 11:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba2dfea6299'
down_revision = '44f54e3bdefe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加新字段到 tasks 表
    op.add_column('tasks', sa.Column('completion_note', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('screenshots', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('related_bug_ids', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('actual_hours', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'actual_hours')
    op.drop_column('tasks', 'related_bug_ids')
    op.drop_column('tasks', 'screenshots')
    op.drop_column('tasks', 'completion_note')
    # ### end Alembic commands ###
